{{- if .Capabilities.APIVersions.Has "templates.gatekeeper.sh/v1" }}
apiVersion: templates.gatekeeper.sh/v1
{{- else }}
apiVersion: templates.gatekeeper.sh/v1beta1
{{- end }}
kind: ConstraintTemplate
metadata:
  name: gkingressannotations
spec:
  crd:
    spec:
      names:
        kind: GkIngressAnnotations

  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package ingressannotations

        ingress_annotations = {k |
          input.review.object.metadata.annotations[k]
          contains(k, "ingress.kubernetes.io")
        }

        # These annotations have been disabled due to CVE-2021-25742
        disabled_annotations = {
          "auth-snippet",
          "configuration-snippet",
          "server-snippet",
          "modsecurity-snippet",
        }

        violation[{"msg": msg}] {
          input.review.object.kind == "Ingress"
          count(ingress_annotations) > 0
          found := {a |
            ingress_annotations[k]
            sL := split(k, "/")
            count(sL) == 2
            sL[1] == disabled_annotations[_]
            a = sL[1]
          }

          count(found) > 0
          msg := sprintf("has disabled annotations: %s", [sort(found)])
        }
